services:
  - type: web
    name: yt-auto-bot
    env: node
    region: frankfurt
    buildCommand: |
      apt-get update
      apt-get install -y python3 python3-pip ffmpeg
      pip3 install yt-dlp
      npm install
    startCommand: "npm start"
